// server/app.js — Express app factory.
// Exports the configured Express `app` (no .listen()) so the same code runs:
//   - locally via server/index.js -> app.listen()
//   - on Vercel via api/index.js  -> exported as a serverless function
import "./env.js";
import express from "express";
import cors    from "cors";

import { pingDatabase } from "./db.js";
import { allowRoles, authRouter, requireAuth, ROLES } from "./auth.js";
import { corsOptions, rateLimit, securityHeaders } from "./security.js";

import dashboardRouter   from "./routes/dashboard.js";
import stationsRouter    from "./routes/stations.js";
import chargersRouter    from "./routes/chargers.js";
import usersRouter       from "./routes/users.js";
import sessionsRouter    from "./routes/sessions.js";
import paymentsRouter    from "./routes/payments.js";
import maintenanceRouter from "./routes/maintenance.js";

// ── Cloud-project routes ────────────────────────────────────────────────────
// These four are what turns the EDS 6343 database project into a cloud project:
//   attachments → unstructured file intake (object storage + async extraction)
//   files       → signed downloads out of object storage
//   telemetry   → the high-volume, spiky ingest path
//   invoices    → PDFs generated by the billing worker
//   ops         → live queue / worker / cache metrics for the Cloud Ops page
import attachmentsRouter from "./routes/attachments.js";
import filesRouter       from "./routes/files.js";
import telemetryRouter   from "./routes/telemetry.js";
import invoicesRouter    from "./routes/invoices.js";
import billingRouter from "./routes/billing.js";
import opsRouter         from "./routes/ops.js";


export const app = express();

// ── Middleware ──────────────────────────────────────────────────────────────
// Native development is reached directly, so trusting arbitrary forwarded IPs
// would let a client evade the rate limiter. Docker sets TRUST_PROXY=true
// because Nginx is the single known hop in front of Express.
app.set("trust proxy", process.env.TRUST_PROXY === "true" ? 1 : false);
app.use(cors(corsOptions()));
app.use(securityHeaders);
// Telemetry batches of 500 beats are a few hundred KB, past Express's 100 KB
// default. Raised deliberately, and capped so a client cannot post 50 MB of
// JSON and make the API server do unbounded parsing work.
app.use(express.json({ limit: "2mb" }));

// ── Public routes ───────────────────────────────────────────────────────────
app.get("/api/health", async (_req, res) => {
  try {
    const db = await pingDatabase();
    res.json({ status: "ok", db });
  } catch (err) {
    res.status(500).json({ status: "error", error: err.message });
  }
});

app.use("/api/auth", rateLimit({ max: 10, namespace: "auth" }), authRouter);

// A signed URL is already a short-lived capability, and browser image/PDF
// requests cannot attach our bearer token. Keep this route outside the auth
// wall while retaining its HMAC signature and expiry checks.
app.use("/api/files", filesRouter);

// ── Protected routes ────────────────────────────────────────────────────────
app.use("/api", rateLimit({ max: 1_200, namespace: "api" }), requireAuth);

// ── Who may reach what ──────────────────────────────────────────────────────
//
// Every business router below names its roles explicitly. `/api/dashboard` used
// to be mounted bare, and because a missing guard means "everybody", a field
// technician could read revenue by city and the cost of every recent charging
// session — while the same data was correctly refused to them at /api/sessions
// and /api/payments. The detail was locked and the aggregate was wide open.
//
// The lesson is worth stating plainly: an omitted guard fails OPEN. So no
// router is mounted without one, and `npm run doctor` asserts it.
const ALL_STAFF = [
  ROLES.OPS_MANAGER, ROLES.TECHNICIAN, ROLES.FINANCE, ROLES.SITE_HOST, ROLES.VIEWER,
];

// Physical infrastructure. A technician needs it to do the job and a site host
// needs it for their own car park. The routers filter rows by company for
// hosts, so "all staff" here does not mean "all data".
app.use("/api/stations", allowRoles(...ALL_STAFF), stationsRouter);
app.use("/api/chargers", allowRoles(...ALL_STAFF), chargersRouter);

// Operational overview. Each role gets its own shape of it; a technician has no
// business seeing revenue, so they are not admitted at all.
app.use("/api/dashboard",
  allowRoles(ROLES.OPS_MANAGER, ROLES.FINANCE, ROLES.SITE_HOST, ROLES.VIEWER),
  dashboardRouter);

// Customer and money data. Never the technician; never the site host either —
// a host may see that their bay was used, not who used it.
app.use("/api/users",    allowRoles(ROLES.OPS_MANAGER, ROLES.VIEWER), usersRouter);
app.use("/api/sessions", allowRoles(ROLES.OPS_MANAGER, ROLES.FINANCE, ROLES.VIEWER), sessionsRouter);
app.use("/api/payments", allowRoles(ROLES.OPS_MANAGER, ROLES.FINANCE, ROLES.VIEWER), paymentsRouter);
app.use("/api/invoices", allowRoles(ROLES.OPS_MANAGER, ROLES.FINANCE, ROLES.VIEWER), invoicesRouter);

// Work orders: managers dispatch, technicians work their own, hosts see what is
// broken on their own sites.
app.use("/api/maintenance",
  allowRoles(ROLES.OPS_MANAGER, ROLES.TECHNICIAN, ROLES.SITE_HOST, ROLES.VIEWER),
  maintenanceRouter);

app.use("/api/attachments", allowRoles(ROLES.OPS_MANAGER, ROLES.TECHNICIAN), attachmentsRouter);
app.use("/api/telemetry",   allowRoles(ROLES.OPS_MANAGER, ROLES.VIEWER), telemetryRouter);

// Finance: the money inbox and the reconciliation view. Operations can raise a
// request on a driver's behalf but cannot approve one — whoever asks and
// whoever approves have to be different people.
app.use("/api/billing",
  allowRoles(ROLES.OPS_MANAGER, ROLES.FINANCE, ROLES.VIEWER),
  billingRouter);

// Infrastructure internals — not a business view at all.
app.use("/api/ops", allowRoles(ROLES.OPS_MANAGER, ROLES.VIEWER), opsRouter);

// ── Health check ────────────────────────────────────────────────────────────
// ── Centralized error handler ───────────────────────────────────────────────
// Every route `catch`es with `next(err)` and lands here. We surface the real
// MySQL error code/message to the browser so the user sees what's wrong
// instead of a generic "Failed to fetch …".
// eslint-disable-next-line no-unused-vars
app.use((err, _req, res, _next) => {
  console.error("[api error]", err);

  // Upload problems are the client's fault, not ours - answering 500 would make
  // the browser retry a file that will never be accepted.
  if (err.code === "LIMIT_FILE_SIZE") {
    return res.status(413).json({ error: "file too large (max 15 MB)", code: err.code });
  }
  if (err.code === "LIMIT_FILE_COUNT" || /unsupported file type/.test(err.message ?? "")) {
    return res.status(400).json({ error: err.message, code: err.code });
  }

  res.status(500).json({
    error: err.sqlMessage || err.message || "Internal server error",
    code:  err.code,
  });
});

export default app;
